print ("Hello World!")
print ("Wie ist dein Name?")
name = input()
print ("toll dich kennenzulernen, " + name)
print ("Wie alt bist du?")
age = input ()
print (age + "Ist ja ein tolles Alter")
print ("Was sind deine Hobbys?")
hobby = input ()
print ("Ich mag auch " + hobby)
