import time

print ("Was hast du, wenn du im Auto Tomaten isst?")
input ()
print ("Automaten")
print ()
print ("------------------")
time.sleep(2)
print ("Was sitzt auf dem Baum und macht AhAh")
input ()
print ("Ein Uhu mit Sprachfehler!")
print ()
print ("------------------")
time.sleep(2)
print ("Klopf Klopf.")
input ()
print ("Feuer")
input ()
print ("Feuer wer")
time.sleep(2)
print ("Ja, der braucht ein wenig länger")
time.sleep(2)
print ("-BdumTS")
time.sleep(4)
